### ISSUE TITLE
Sprite; assigning a texture should refresh uv

### ISSUE THREAD

**Issue by DjPale** [underscorediscovery/luxe#160]
If assigning a new texture to a sprite (```sprite.texture = ...```) with different size, the uv coordinates do not get updated. The result is that the texture looks stretched / cut-off. To reproduce, create 2 textures with difference across the POT boundaries (like 64 and 65), assign the first upon creation of the Sprite and the second at runtime.

**Comment by underscorediscovery** [comment]
This issue is a bit more nuanced than it seemed, and won't be handled (at least not short term). 

To fix this, It has to make the assumption that the texture is 1:1 with the geometry, which just can't be done without forcing it, which is something luxe will avoid doing.

Consider: 
`var sprite = new Sprite({ texture: lava_frame0 });`
`sprite.uv.w = lava_frame0.width * 4; //4x tiling`
`sprite.uv.h = lava_frame0.height * 4;`
and then:
`sprite.texture = lava_frame1; //woops, broken`

Any assumptions like these aren't allowed by luxe design, actions are explicit, not behind your back or trying to be smart. 

It stands to reason then, that:
 - if you're explicitly changing the texture
 - and this action will result in incorrect uv
 - you must also update the uv to match the change, explicitly
 - i.e `sprite.uv.set(0,0,texture.width,texture.height);`

I'd be interested in opinions, but it's how luxe works and will continue to stick to these patterns, the extra line of code is worth the inconsistency and mess :)
