### ISSUE TITLE
Window events web resize bug

### ISSUE THREAD

**Issue by RedSQ** [underscorediscovery/luxe#236]
Window resize events works incorrect on web target. (Check [luxe/tests/features/window_event](https://github.com/underscorediscovery/luxe/tree/master/tests/features/window_events)). Probably it's happened because of snow WindowSystem implementation.

Check [line 561 in WindowSystem](https://github.com/underscorediscovery/snow/blob/master/snow/platform/web/window/WindowSystem.hx#L561).

I've tried to fix it, simply removed iteration is fs_windows array, but I'm not sure if it's correct.

**Comment by underscorediscovery** [comment]
Could you please elaborate on what you are actually expecting and what you are seeing? :) 

I don't see anything wrong here from the quick event test, I pushed [an updated version](https://github.com/underscorediscovery/luxe/commit/38e00fd) - run it and press the R key. When the _actual_ canvas resizes, the events are fired. The browser window doesn't resize the child elements unless there is css to do that, by default there is not.

Try also the [snow sink test](https://github.com/underscorediscovery/snow/tree/master/tests/features/0_sink), 
- run with `flow build web --timeout 0`
- press alt+enter to go window fullscreen
- resize the window or toggle alt+enter
- note that the box always bounces back on the "right edge"

If you could elaborate on what you expected, perhaps that might clear things up?

**Comment by RedSQ** [comment]
When I resized a browser window I expect that a window resize event should be fired, so it would make possible to change a canvas size and fit it into browser window. But only a window(canvas) move event has been called, instead of resize event.

**Comment by underscorediscovery** [comment]
Yea, this is expected because if you wanted the BROWSER resize event - it is not the event that comes from the _snow window_ itself. _snow window = canvas element_. If the browser resize fires on the window event, it would break all the logic across web vs other targets, especially when a user starts adding logic or css to the canvas (which is normal) and this is bad.

I can see the value in wanting to know when the browser is resized, but I will have to see if this fits anywhere in snow level - for example in regular haxe code you have access to `js.Browser.window.addEventListener('resize', function(e){ trace(e); } );` or similar, using `#if js` that would give you the event you wanted in the mean time?

**Comment by RedSQ** [comment]
Yeah, sure, sorry, my bad, I misunderstood an architecture a little bit so it's little bit confused me. Thank you for help. And your explanation is great. I think you should write more articles about luxe.

**Comment by underscorediscovery** [comment]
No problem!
I will write A LOT more when things are a bit more finalized, as if they change it's 2x as much work :)
The alphas won't be too many or too long, and by beta everything will be written out.

If you have specific questions, feel free to ask them on github, the snowkit.org site or the [chat](https://gitter.im/snowkit/public) and I'll be happy to answer short term.
