### ISSUE TITLE
Physics; Nape; DebugDraw; Creating geometry every frame is very slow

### ISSUE THREAD

**Issue by ubald** [underscorediscovery/luxe#252]
I don't know enough about the engine to work on a solution but the DebugDraw for Nape is constantly creating geometry and with 64 circles only it becomes almost unresponsive (on a mac pro ;)).

**Comment by underscorediscovery** [comment]
yepyep, its not meant to be used as a full visualizer for the world state, it was just a quick implementation to get out the gate.

There are some nape related things in progress, a few components and such, which include a debug shape draw that isn't recreated all the time (because it knows the state, where as the debug draw would double the work/storage if it were keeping track of everything you're doing as geometry, it can't make that assumption yet).

I'll leave this open, but further focus sheets will tie up all these loose ends on the tertiary modules.

**Comment by underscorediscovery** [comment]
I should add - You shouldn't expect to release a game drawn via the debug draw tool - you need to have your own geometry etc. The general idea is that you're using it for debug, and your visuals/game sprites/geometry are going to do the drawing. 

Maybe this will be a good short term solution, where items can be excluded easily to only debug the ones you're testing at the time.

**Comment by ubald** [comment]
Of course I wouldn't release something based on that. I'm not even making a game, just testing out the engine mixing nape and steering behaviours together and the debug shapes were just what I needed.

**Comment by underscorediscovery** [comment]
Yea, I wasn't implying you were using it for a game, hah, just noting for why I haven't fussed with it much yet - and how I use it.

**Comment by ubald** [comment]
I was more trying to use it as a Haxe-OpenFrameworks-kind-of-thing. Anyway thanks for the answer!

**Comment by underscorediscovery** [comment]
makes sense, 
I was thinking about it, a persist style would be fine (given my above description it actually would be inconsequential of the overlaps). I'll see if one of the community members are interested in tackling this (like @whuop is working on the components along the way), maybe we can sneak it in.

**Comment by KeyMaster-** [comment]
I already got a simple component running that generates geometry for a shape. Maybe I could expand that to do the whole of what debug draw is currently showing.

**Comment by underscorediscovery** [comment]
This should be much better since https://github.com/underscorediscovery/luxe/commit/c23809b46b1931d8078d37849b4320c94dd37d43

@KeyMaster- did the work here and made the cache-based version. 

Read the commit log to see how to use it now - or see the tests/features/physics_nape as it was updated to match!

I'll close this for now, as it relates directly to the fixes, the other performance side effects of this type of drawing is in the renderer, which will address that on it's own.
