### ISSUE TITLE
States; setting an invalid state fails silently

### ISSUE THREAD

**Issue by anissen** [underscorediscovery/luxe#253]
Currently, setting an invalid state causes all states to be exited. This makes it hard to catch a typo or inconsistency in the state identifiers.

The issue is illustrated in the following example:
```haxe
var states = new States({ name: 'state_machine' });
states.add(new State({ name: 'PlayScreenState' }));
states.set('PlayScreenStat'); // Typo! No state is set
```

The issue is even more dangerous when the identifiers are scattered though-out the code.

**Comment by underscorediscovery** [comment]
The "setting invalid state" to exit is part of the usage atm - in other words, `states.set('')` will exit any modal state (leaving transient states alone). I use this quite a bit, but I agree that the other is painful.

Here's some ideas till this gets some attention:

**try a static identifier rather than a string** 
`MyState.stateid` as `public static var stateid = 'PlayScreenState';`

Then do `states.set(MyState.stateid)` which prevents typos.

**you can do the same concept with abstract enums**   
```
@:enum abstract MyStates(String) from String to String {
   var PLAY = 'PlayScreenState;
}

states.set(MyStates.PLAY);
```

**you can enable state logging to see what's happening**    
add 
`flags:['--macro luxe.Log.level(2)', '--macro luxe.Log.filter("states, state")']` 
to your flow file **build** node. 

These names are based on the file name of the class, and allow seeing a slice of the logs, there is also level up to 5 and luxe.Log.exclude which can filter the other way. They are just a comma separated string list of things to filter.

---

States will get some clarity a bit down the road, though, as a more explicit exit would be ideal.
