### ISSUE TITLE
Luxe.utils.random on mac generates out of range values

### ISSUE THREAD

**Issue by pixelsyntax** [underscorediscovery/luxe#256]
Luxe.utils.random.int and .float generate out of range values on mac when supplying min and max arguments, using Luxe version 1.0.0-alpha.1+781304b460, freshly checkout out a few hours ago.

Adding the following to the default empty project's Main.hx ready function

    var max : Float = 0;
    for ( i in 0...1000 ){
        var t = Luxe.utils.random.float( 0, 1 );
        if ( t > max )
            max = t;
    }
    trace( max );

Should give an expected result of a float less than 1, (for example 0.9888), but the actual output when targeting mac is

    Main.hx:16: 1.99814974772675

It appears that the generator is returning values approaching twice the value of the max argument. The same happens with .int(min, max)

Targeting web does not exhibit this behaviour and works as expected.

**Comment by underscorediscovery** [comment]
ah, interesting, I had thought I saw something odd when using it but haven't had time to write some tests to verify.

I think it's doing [0,1] inclusive, rather than [0,1) range, so it gets 'double', but if you tried a large running set over say 0,10 i think the max would be 11, but I haven't confirmed.

I wanted to write a test to visualize a large set of numbers as points and graphs, so we can see what it's actually up to.

**Comment by underscorediscovery** [comment]
@pixelsyntax can you run the tests/features/random and let me know what you see?

I suspect this is a 3.2.0 / 3.1.3 distinction, testing on mac I get values like this from the test.

![screenshot 2015-04-17 17 41 37](https://cloud.githubusercontent.com/assets/236374/7210087/5ca92102-e529-11e4-8310-1b76ef9197e6.png)

**Comment by underscorediscovery** [comment]
I am not reproducing this on any platform now (but I did encounter it before), on haxe 3.1.3, haxe 3.2.0 mac/web/windows the results are all within range.

let me know if you still see it!

**Comment by pixelsyntax** [comment]
Confirmed as fixed for me using newest git version snowkit libs at time of posting
