### ISSUE TITLE
Tilemap; haxe 3.1.3 Bytes.getInt32 error in TiledLayer 

### ISSUE THREAD

**Issue by alesegdia** [underscorediscovery/luxe#263]
So there is an error on `Bytes.getInt32` function because it doesn't exist in Haxe 3.1.3 anymore. I sent a new pull request to fix this by reading the 4 bytes separately with new `Bytes.get` function and building the integer with this 4 bytes using bit operations. The only problem could be related to endianness as I said on the pull request. Tested the pull request by loading a .tmx map with the map data encoded on base64. 

Just wanted to place it here to keep a record of the error.

**Comment by underscorediscovery** [comment]
I should be able to fix this today, but for anyone running into this until then, the haxe 3.2.0 RC.2 is quite stable with luxe/snow and is good to update to if you can. [See this post for more](http://snowkit.org/2015/03/16/haxe-3-2-0/)

**Comment by alesegdia** [comment]
You milestoned this to LD32 prep! good because I was going to ask about it.

**Comment by underscorediscovery** [comment]
I appreciate the PR! Unfortunately the changes aren't ideal, it does a few redundant calculations and bypasses the haxe api's which I want to avoid. The actual fix is using the 3.1.3 specific api, I just haven't pushed it yet because I wanted to test it quick, but have been busy with the other tasks so long.
