### ISSUE TITLE
Camera_scale mode naming convention

### ISSUE THREAD

**Issue by JunoNgx** [underscorediscovery/luxe#272]
While the work-in-progress ```camera_scale``` is working well and satisfying the general needs of most games, I do think their names should be more conventional.

* ```cover``` => ```fill```
* ```contain``` => ```stretch```
* ```fit``` as of now, is fine.

This scale naming convention so far has been used beyond game engines (i.e. Windows wallpaper setting) for a long time. Unless there is some rationales (that I'm currently not aware of), I don't think this is assistive or helpful for now. This would save developer remembering and questioning "What does this scale correspond to?".

**Comment by underscorediscovery** [comment]
It's similar to the CSS background-size property.

The scale mode is (as with anything) a literal english word and would correlate to that in meaning. I prefer names that do not become ambiguous, especially, when they can become that way within their own context.

The suggested names have too much overlap that I dislike, for example "fill" and "stretch" mean the same thing to me. "stretch" doesn't seem ideal either, because a scaled image will be stretched, no matter what mode you choose. It's also something that may or may not manifest conceptually - for example, if your view is 1:1 with the window, there is no "stretch"ing. 

In the context of what the flag is doing, I prefer the ones that are there.
I chose them quite conscientiously, so we'll stick with them for now. 
I appreciate the feedback!

**Comment by JunoNgx** [comment]
I was not aware that these flags were also used in CSS.

On the other hand, rationales noted. Thanks for the quick response.
