### ISSUE TITLE
Have on*pressed() functions for classes like Entity, Component

### ISSUE THREAD

**Issue by Aleph0Null** [underscorediscovery/luxe#276]
Currently I'm doing `if (Luxe.input.*pressed('...'))` inside `on*down()`, having on*pressed() would save lots of function calls. Maybe have interfaces for the common event slot functions to ensure they're present where they can be used.

(Guess this is probably on the to-do list? But putting it here anyways.)

Edit: And maybe rename the `on*up()` functions to `on*released()`, to make them consistent with `Luxe.input`. Adjectives (down, up) refer to the current state of the input medium, while past tense (pressed, released) refer to the prior state.

**Comment by underscorediscovery** [comment]
Actually, you're using two different usage patterns and conflating them as one.

Don't call Luxe.input calls inside of the _on_ handlers of the same type - that's a bit of an anti pattern.

There are two types: event based, and immediate query.
Event based is the callbacks, i.e on___ where ___ is the event.
Immediate query is "anywhere", where you ask for the state. 

Secondly, up and released are not the same concept. Immediate queries include the concept of "released this frame" or "pressed this frame". It's possible that because input is dispatched when they happen, they are past tense because they're explicitly asking about a specific type of state. 

"Is the key down" (or not down) doesn't care about the frame, only the state, so a key that is already held down would return true every frame. i.e, you'd get multiple esc releases per second (60 usually), not just the one. The released/pressed are set for one frame, rather than a state flag.

Generally, you use the event handlers, which exist on every class that usually needs them (State, Scene, Entity, Component, Game, etc). The immediate queries are just a different pattern, and have different uses. 

Personally I avoid the immediate queries except for quick things, because it often leads to hamming input code where it shouldn't be and creating more rigid input mappings that can be harder to make configurable. Because the input events happen as soon as they are triggered, it also means event handlers have less inherent latency, your state will always be set as soon as it happens, rather than potentially in the next visible frame after.

**Comment by Aleph0Null** [comment]
> Actually, you're using two different usage patterns and conflating them as one.
I'm aware of the distinction. I need to check for pressed and released. But I can't solely use event-based handling*, because Component doesn't support `onpressed`. If I use solely immediate query, I'd have to query every frame via `update()`, querying only when a key is down is still an improvement over that.

(*technically, I could, if I keep track of which frames the keys are down and up, and infer pressed from that. But that's just being silly.)

> "Is the key down" (or not down) doesn't care about the frame, only the state, so a key that is already held down would return true every frame

Right. But `Component`'s `onkeyup()` isn't called every frame when a key is up, it's called whenever a key is *released*. (I haven't tried the other classes, so I'm assuming the behaviour is the same for them) Granted, it's silly to fire an event whenever any of the keyboard's 100+ keys are up, so if you sit and think about it, you can tell what the function's supposed to do. But it's more natural to keep the naming consistent with `Luxe.input`s use of '*release', and so not have to sit and think about it, or already be used to the naming inconsistency.

**Comment by Aleph0Null** [comment]
Reread your reply and did some testing. Turns out `on*down()` isn't called every frame a key is held down. It's called on the initial press (lower latency here), then after that only when Luxe decides it's time to 'repeat' the 'keypress' (so higher latency afterwards). Like when you hold down a character key in most text editors. In particular, when holding down a key, there's a significant pause between the first and second `on*down()` calls.

I think I understand what you were trying to explain. `Luxe.input` stores information about the state of the input during each frame (as I expected), whereas the `*Event` dispatches occur at Luxe's discretion.

Sorry for the confusion!

But:
 - it's still useful to have `on*pressed()`, that's only called when a key is pressed and not triggered again by that same key until after it's released and pressed again.
  - I assumed from the name `on*down()` that they were called every frame the input is held down, partly because of the similarity with `Luxe.input`'s `*down` names. Maybe the code comments should be more detailed about their behaviour, in particular mention that they're not called every frame?

**Comment by underscorediscovery** [comment]
Some additional notes,

- All behaviour of key input and friends is de facto, these are OS level events, consistent across every OS, browser, etc. I haven't deviated from conventions in naming nor behaviour. I also won't be, as they are existing “standard” (and they aren't inconsistent in their layout, as they don't overlap in this way).

>only when Luxe decides
> at Luxe's discretion

- Key repeats (and all other events) come from your operating system keyboard driver. The events are directly propagated into usable form, as they happen. There is no luxe code doing anything to the input, except for the immediate api's, which collect state and expose it for convenience.

> it's still useful to have on*pressed()

- A key down event is identical in behaviour here, the same key cannot send another key down until the key is released (logically/physically) with one exception - key repeat events. In the event of this specific "soft" case, the `repeat` flag on the key event is set to true. If you don't care for the repeat specific events, ignore those :) 

   I'd rather not add redundancy over an existing pattern. If anything, a config for rejecting repeated keys internally could be added but I generally prefer explicit vs implicit control, so it won't be added just yet. What you are after seems pretty clear, and right there. Since you mentioned you're abstracting this, you could always emulate the behaviour on your level as well.

> Maybe the code comments should be more detailed

- I can always add more details, sure.

**Comment by Aleph0Null** [comment]
> All behaviour of key input and friends is de facto, these are OS level events, consistent across every OS, browser, etc. I haven't deviated from conventions in naming nor behaviour. I also won't be, as they are existing “standard” (and they aren't inconsistent in their layout, as they don't overlap in this way).

> Key repeats (and all other events) come from your operating system keyboard driver. The events are directly propagated into usable form, as they happen.

Thanks for the info, I hadn't realized all this. I'm a hobbyist who's only recently started really looking into what industry does, often it feels like people respond assuming I have the same experiences they do (even when they know I'm new to things).

Btw I really appreciate all the detailed explanations! In the guides as well, e.g. back when I was trying to figure out Unity, an explicit description of the component pattern would have saved me a lot of time and frustration.


> If anything, a config for rejecting repeated keys internally could be added but I generally prefer explicit vs implicit control, so it won't be added just yet. What you are after seems pretty clear, and right there. Since you mentioned you're abstracting this, you could always emulate the behaviour on your level as well.

Yeah. It's not a major problem, just a shame that currently my code will have to run lots of unnecessary function calls.

**Comment by underscorediscovery** [comment]
No worries, I try to be aware of that constantly, but the edge goes both ways, if you explain "obvious" things it's also demotivating (as is not explaining when needed).

In general all these types of detail and reasoning _will_ be documented out in guide form, and will cover the whole base line of why too (the "design" links on the home page of the docs alludes to this) but as with much of the alpha status, these things are a work in progress and don't exist yet as a side effect of time.

There was a guide [here](http://luxeengine.com/docs/guide.input.html) which was outdated - but i've updated it now and will add more information in future.
