### ISSUE TITLE
preloading tilemaps causes a crash on iOS (uncaught exception of type Dynamic)

### ISSUE THREAD

**Issue by jonathanhirz** [underscorediscovery/luxe#285]
test case: https://github.com/jonathanhirz/ios_crash_luxe_tilemap

project builds fine and runs on Mac native. causes a crash on iOS. I think I narrowed down the issue to preloading the tilemap in config. wasn't sure if this was a luxe or snow issue, sorry if it's in the wrong spot

**Comment by underscorediscovery** [comment]
Did you run with --debug (enabled via debug profile in xcode)? 
Usually the crash with debug at minimum would drop you into a callstack on c++ code, and usually would have a haxe callstack as well, so I'm curious.

**Comment by jonathanhirz** [comment]
I think so, it crashes and I think Xcode is in a debugger...I posted a picture of it in gitter but I'm not really familiar with debuggers or how to dig into the crash

**Comment by underscorediscovery** [comment]
Actually what it's throwing on is [this line](https://github.com/underscorediscovery/luxe/blob/master/luxe/Core.hx#L294), which is odd that it doesn't show the throw message in the log since it's a regular haxe throw.

I added a log message there as well quick to see if you can see which one is failing, as I can't run it on iOS immediately. Let me know what it says?

**Comment by jonathanhirz** [comment]
Core.hx:277:      i / luxe / / OpenGL ES 2.0 Apple A8 GPU - 53.13 / OpenGL ES GLSL ES 1.00 / Apple A8 GPU / Apple Inc. /
Core.hx:294:      i / luxe / config / preload / failed to load / { total => 3, index => 1, error => error(data_load file cannot be opened assets/tilemap.tmx), load_id => default_parcel}
libc++abi.dylib: terminating with uncaught exception of type Dynamic

**Comment by underscorediscovery** [comment]
It does help in fact, the `data_load` api is the lower level one. It accepts the "actual path" (adjusted for platform specific differences and locations by the asset system, by snow). The fact that data_load is getting the "asset id" and not the "asset path" is a hint at what could be wrong (as iOS does differ this way).  

With that, it was an easy fix. Strange catch though, it seems that text based assets were funky on iOS since the asset refactoring! I must have been unfortunate to run an older build when I tested at the time.

**Comment by jonathanhirz** [comment]
Works great! Thanks
