### ISSUE TITLE
Camera; expose ortho projection parameters

### ISSUE THREAD

**Issue by ivcoar** [underscorediscovery/luxe#344]
Custom ortho projection parameters in CameraOptions, instead of using the viewport size or using a custom projection. For example, use a ortho projection that ranges from `-size * aspect` to `size * aspect` in width and from `-size` to `size` in height, being `size` another parameter. The equivalent with a custom projection would be 
`projection_matrix.makeOrthographic( -aspect * size, aspect * size, -size, size, near, far);`

**Comment by underscorediscovery** [comment]
I'm still thinking over how to best resolve this btw :+1:

**Comment by underscorediscovery** [comment]
@ivcoar I've added an initial implementation for testing. 

The idea being that IF you set the `ortho_left`/`ortho_right`/`ortho_top`/`ortho_bottom`, they will be used and otherwise the default of the viewport sizes will be used. The idea being control and flexibility, the size parameter specifically is an app implementation detail that you would do on your application end.

So to use it, you set these properties, and each time you do they will update the matrix parameters. This also means that if the values change implicitly (like via a window resize) you'll have to update the `camera.ortho_right` etc manually as expected.

Can you try that out when you can?
