### ISSUE TITLE
entity.get() results in too much recursion on web target and game crash

### ISSUE THREAD

**Issue by alexoro412** [underscorediscovery/luxe#365]
So I created a sprite, and then gave it a nape box collider. I then tried getting that collider from the entity. I also tried getting the list of components from the entity. 
On the mac target, this worked perfectly fine. When targeting web, however, I received errors such as "too much recursion"(waterfox) and "maximum call stack exceeded" (chrome). According to the errors, js_Boot.__string_rec is calling itself too much.
![screen shot 2016-03-21 at 12 06 59 am](https://cloud.githubusercontent.com/assets/8892294/13911635/dcedd0cc-eef8-11e5-98a2-af163416a613.png)

code:

```
player = new luxe.Sprite({
	name:'player',
	texture: Luxe.resources.texture('assets/bird.png'),
});

var box_col = new BoxCollider({
	name:'collider',
	body_type:BodyType.DYNAMIC,
	material:Material.wood(),
	x:100,y:100,w:50,h:50,
});

player.add(box_col);

trace(player.get('collider'));
trace(player.components);
```

output on mac target:
```
Main.hx:73: BoxCollider
Main.hx:74: {collider => BoxCollider}
```

**Comment by underscorediscovery** [comment]
It seems to be related to how luxe/structural/OrderedMap.hx `toString` is implemented, the js code for that section must be calling itself. It seems like it's a bug from the haxe js generation but is triggered by the calling code, so the best option is to further try to isolate the behaviour and report an issue on the haxe side when we have a test case. 

I'll have a look soon, but the trigger comes from printing the components map I think - which is also potentially indirectly triggered by printing the component (since it may reference it's parent container).
If you don't print them, you should be able to get by. If you want to move forward, try printing just the name/id `if != null` or similar. 

Thanks for the report

**Comment by underscorediscovery** [comment]
@alexoro412 if you update, I've fixed it in a direct way but I'll keep this open to further investigate later.

**Comment by alexoro412** [comment]
Thank you!
