### ISSUE TITLE
Tilemap: add_tileset() does not automatically set first_id

### ISSUE THREAD

**Issue by whuop** [underscorediscovery/luxe#367]
When using more than one tileset with Tilemap, the id's for all tilesets except the first one are incorrect. Tileset.first_id is not changed from its initial value of 1, the first_id of the tilesets has to be set manually for them to work. 
Example:
if first tileset is 16 * 8 tilesets wide / high. first_id must manually be set to 128 on the second tileset, otherwise it won't work correctly.

Don't know if this is intentional or not.

**Comment by underscorediscovery** [comment]
There is no internal logic for what order the user considers the tilesets to be in, and there can't be. You need to specify the `TilesetOptions` on creating a tileset to be the values you expect them to be, otherwise they will use the defaults (which is where the 1 comes from). 

i.e it is explicit, you need to specify the options for your tileset, it will not guess what you are trying to do.
