### ISSUE TITLE
Removing a child entity from its parent does not add the child back to the scene_root

### ISSUE THREAD

**Issue by wetlag** [underscorediscovery/luxe#384]
Not sure if it's intended behavior, but when I set a child entity's parent to null, the child position doesn't get updated properly when I tween it. 

I think I fixed it by adding the following line in _remove_child:
    function _remove_child(child:Entity) {
        child.scene_root.add(child);
        children.remove(child);
    }

**Comment by underscorediscovery** [comment]
hmm I think you're right on the issue, but the suggested fix might not be ideal - since it immediately sets the new parent after that, it would be thrashing in and out of the scene root when it can already tell that there is a new parent. meaning the fix would likely be better placed in the set_parent area, where the transform parent is also null:

```
        if(parent != null) {
            parent._add_child(this);
            transform.parent = parent.transform;
        } else {
            transform.parent = null;
            scene_root.add(this);
        }
```

Keep in mind the entity stuff is quite simple and not well fleshed out at present, it will get a focus soon enough and be made more consistent.

**Comment by underscorediscovery** [comment]
Can you let me know if that helps?
