### ISSUE TITLE
Web target bug with textures

### ISSUE THREAD

**Issue by CamperPR** [underscorediscovery/luxe#391]
So, sometimes i need already loaded sprites without textures. And then when i importing them, sprites displaying on another place and having another size.

**Comment by underscorediscovery** [comment]
I'd like to better understand your issue, but I am having trouble seeing what you mean. Could you make a simple test case in the empty project that demonstrates the bug please? Thanks!

**Comment by CamperPR** [comment]
```haxe
class Main extends luxe.Game 
{
	override function ready() 
	{
		var sprite:Sprite = new Sprite({
			pos: Luxe.screen.mid,
			size: new Vector(600, 800)
		});
		
		sprite.texture = Luxe.resources.texture("assets/f001.png");
	}
	
	override public function config(_config:GameConfig):GameConfig 
	{
		
		_config.preload.textures = [
			{ id: "assets/f001.png" }
		];
		
		return _config;
	}
}
```

https://pp.vk.me/c615817/v615817758/1b969/yGVmoS1DXJg.jpg

**Comment by underscorediscovery** [comment]
I think I see now thanks! 
When drawing, the `sprite.uv` rectangle is used to decide what part of the texture to draw.
On web target, textures are automatically created at the next highest "power of two".

`800` -> `1024`
`600` -> `1024`

This is needed for how the web target works with WebGL - and normally all of the situations where this matters are handled for you. However, because `texture` [is null when you create the sprite](https://github.com/underscorediscovery/luxe/blob/master/luxe/Sprite.hx#L57-L59) it does not know what `uv` to put, so it leaves the geometry to render "the whole texture".  On native, this means you see 600, 800. On web this means you see 1024, 1024. 

The fix for your case, **set the uv to the correct size if you set the texture later**, 

```haxe
override function ready() 
    {
        var sprite:Sprite = new Sprite({
            pos: Luxe.screen.mid,
            size: new Vector(600, 800)
        });

        sprite.texture = Luxe.resources.texture("assets/f001.png");
           //make sure texture uv is exact
        sprite.uv = new luxe.Rectangle(new Rectangle(0, 0, sprite.texture.width, sprite.texture.height));
    }
```

Hope that is clear and helps!

**Comment by CamperPR** [comment]
Thanks!
