### ISSUE TITLE
Contributing Collision Guide

### ISSUE THREAD

**Issue by ashes999** [underscorediscovery/luxe#394]
Hi,

I would like to write up a quick (I don't know how accurate it'll be) beginner-ish guide on collision detection in Luxe.

How exactly do I do this? I see there's a `gh-pages` branch, but that looks like generated HTML. I don't see any source files (I also checked the `samples` folder) in the master branch.

**Comment by underscorediscovery** [comment]
Hi, keep in mind that the collision library is actually standalone as well - [see here](https://github.com/underscorediscovery/differ). If there was a particular guide, it may make sense to write it there first. 

The documentation is generated from simple markdown - so just write them in an md file and that would be ready to use in many cases. The actual markdown for the current docs [are here on the docs-src branch](https://github.com/underscorediscovery/luxe/tree/docs-src).

I appreciate the desire to help out, though I do hope you read my thoughts on documenting code and features that are not finalized. I'd hate for you to spend the time on something that I have to discard in the near future without you being aware of the workflow. 

With that in mind, I think the best place for a guide at this time is on the differ side.
Can you expand your thoughts on what you wanted to write about? If you elaborate on what you had hoped to see in the guide, then I can help make sure you're spending your time helping effectively.

Thanks!

**Comment by ashes999** [comment]
Thanks for the quick reply. I took a look again at what you have available (tutorial-style guides like [this one](http://luxeengine.com/docs/guide.two.html) and feature guides like [this one](http://luxeengine.com/docs/guide.sprite.html)) and realized I'm probably way out of my depth.

I essentially figured out how to get collision-detection working by searching the API and looking at different classes and methods. I then wrote [a blog post on it](https://ashes999.github.io/learnhaxe/collision-detection-and-resolution-in-luxe.html). (TLDR: it uses `polygon.testPolygon(targetPolygon)`)

This might not be the best and most fitting method, and it's probably a good idea to mention testing circle vs. polygon and vice-versa. I wanted to write that content up in a small guide.

Perhaps I should just stick to blogging on my own platform for now and wait for more guides to emerge. You set a very high bar there in terms of quality, and I don't want to invest that much time in writing (I'm on my third day of using Luxe today).

I'm closing this issue -- knowing about the `docs-src` branch will be useful for potential future contributers. Thanks for that!

**Comment by underscorediscovery** [comment]
Just curious if you've stumbled into the `tests/` folder?

**Comment by ashes999** [comment]
No, I didn't know about that. Thanks for pointing it out.

When I'm trying to figure something about a new framework, I generally:

- Google and find articles/guides describing how to use it
- Cross-reference any APIs mentioned against the API guide to make sure the information was current
- Implement it and make sure it works
- Look for working examples/templates/samples
- Look at source

I think it's better to have guides and examples. But it's still useful to know where to find the tests.

**Comment by underscorediscovery** [comment]
The tests most people consider example-like, but I get what you mean :)

I've posted extensively on how I work through stuff regarding documentation on the dev logs. It's quite simple in that I don't spend time documenting things I know are changing because it's time I could spend instead finishing the code, which without the code, there is nothing (and nothing to document).

I totally understand that good documentation is a must - as you can tell I value this - it's just a side effect of the timing. The alpha label is quite intentional, and I appreciate your desire for the documentation to be better, and especially to help, but I am in the middle of finalizing the engine design for v1.0 so I am concentrating my thoughts there at the moment. 

I do personally really think documenting things in their transient state leaves more incorrect/slightly wrong/outdated documents strewn around the internet, with a trail of less helpful and hard to undo mess. It also forms some incorrect assumptions about the engine state, implying it's more done than it is, which also over time starts to formalize "how things work" which becomes harder to change without negative feelings (this is most relevant during alpha). To me all the down sides are just much worse than the immediate term benefit of reading a website instead of the code, or an example, or to ask the community or me :)

But - I do hear you and think it's very important. So is when, though!
