### ISSUE TITLE
failed compilation of sample 

### ISSUE THREAD

**Issue by r3d9u11** [underscorediscovery/luxe#417]
Hi. I tried to compile sample [empty_luxe](https://github.com/snowkit/mint/tree/master/tests/test_luxe), but compilation process was failed with error:
```
 - src/snow/types/Config.cpp 
 - src/snow/systems/io/IO.cpp 
Error: In file included from include/snow/core/native/io/IO.h:11:0,
                 from ./src/snow/systems/io/IO.cpp:43:
/home/r3d9u11/.haxelib_repo/linc_sdl/git//linc/linc_sdl.h:3:19: fatal error: /home/r3d9u11/Desktop/mint/tests/empty_luxe/bin/linux64.build/cpp/obj/linux64/__pch/haxe/hxcpp.h: No such file or directory
compilation terminated.
flow / 
 build - stopping because of errors in hxcpp compile, while building arch 64 
```

haxelib:
```
actuate: [1.8.7]
box2d: [1.2.3]
dataTree: [git]
flow: git [dev:/home/r3d9u11/.haxelib_repo/flow/git]
format: [3.3.0]
haxe-crypto: [0.0.7]
haxeui-core: [git]
haxeui-kha: [git]
haxeui-luxe: [git]
haxeui-xwt: [git]
haxity: [git]
hscript: [2.0.7]
hvm: [0.0.2]
hxcpp: 3.2.205 [3.4.49]
hxcs: [3.4.0]
kha: [16.1.2]
layout: [1.2.1]
lime-samples: [3.4.0]
lime-tools: [1.5.7]
lime: [3.7.3]
linc_dialogs: [git]
linc_ogg: git [dev:/home/r3d9u11/.haxelib_repo/linc_ogg/git]
linc_openal: git [dev:/home/r3d9u11/.haxelib_repo/linc_openal/git]
linc_opengl: git [dev:/home/r3d9u11/.haxelib_repo/linc_opengl/git]
linc_sdl: git [dev:/home/r3d9u11/.haxelib_repo/linc_sdl/git]
linc_stb: git [dev:/home/r3d9u11/.haxelib_repo/linc_stb/git]
linc_timestamp: git [dev:/home/r3d9u11/.haxelib_repo/linc_timestamp/git]
luxe: git [dev:/home/r3d9u11/.haxelib_repo/luxe/git]
mint: [git]
openfl-native: [1.4.0]
openfl-samples: [4.7.0]
openfl-tools: [1.0.10]
openfl: [4.8.0]
snow: git [dev:/home/r3d9u11/.haxelib_repo/snow/git]
snowfall: [0.0.15]
stablexui: [git]
systools: [git]
typext: [git]
```

Haxe 3.2.1
Linux Mint 18.1 x64

Thanks.

**Comment by underscorediscovery** [comment]
can you check your hxcpp version? I don't know what breaks between hxcpp latest and haxe 3.2.1 cc @hughsando 

You can try the latest haxe 3.4 with latest hxcpp as well.

**Comment by r3d9u11** [comment]
Yes, this error I have with haxe 3.4 and hxcpp 3.4.49, too.

And than I tried to downgrade haxe to 3.2.1 and hxcpp to 3.2.205 (as described at theme "Step 4. Native platform targets" of [luxe setup guide](https://luxeengine.com/get/))

I'll to upgrade stuff to latest version, and will test it again

**Comment by underscorediscovery** [comment]
Thanks, sorry for the inconvenience, it's rather frustrating because I don't actually know what changed and why it breaks only on some cases. I am hoping @hughsando can shed some insight.

**Comment by r3d9u11** [comment]
Thanks, I'll check it with other versions of packages

**Comment by underscorediscovery** [comment]
You can try define `NO_PRECOMPILED_HEADERS` in the project file, in the defines section. This might help, based on the hxcpp toolchain.

<img width="542" alt="screen shot 2017-02-16 at 11 55 23 am" src="https://cloud.githubusercontent.com/assets/236374/23027460/d4a9016a-f43e-11e6-878b-898b23462397.png">

**Comment by r3d9u11** [comment]
@underscorediscovery Thank you, it works!

**Comment by kamranrad1993** [comment]
i using haxe 3.4.4 and hxcpp 3.4.64
but it gives me the same error
i update hxcpp to 3,4,188 but still not work

**Comment by underscorediscovery** [comment]
Did you try the suggestion in this comment https://github.com/underscorediscovery/luxe/issues/417#issuecomment-280361379

**Comment by kamranrad1993** [comment]
yes i tried it 
but not work

**Comment by hughsando** [comment]
There are some issues with #including hxcpp.h from non-hxcpp gen files.
Is this the case?

The number 1 rules is that hxcpp.h must be the very first thing included, or you must disable PCH.

**Comment by underscorediscovery** [comment]
I had many months back made sure all hxcpp.h was first. The above suggestion disables PCH.

**Comment by hughsando** [comment]
Looks like old code somewhere then?
If you compile with "-D HXCPP_VERBOSE" and post the full command line that causes the error, it might help.

**Comment by underscorediscovery** [comment]
hard to say if it's old code. Here's every extern in use:
- linc_openal / [h](https://github.com/snowkit/linc_openal/blob/master/linc/linc_openal.h#L3) / [cpp](https://github.com/snowkit/linc_openal/blob/master/linc/linc_openal.cpp#L1)
- linc_timestamp / [h](https://github.com/snowkit/linc_timestamp/blob/master/linc/linc_timestamp.h#L1) / [cpp](https://github.com/snowkit/linc_timestamp/blob/master/linc/linc_timestamp.cpp#L1) / [cpp](https://github.com/snowkit/linc_timestamp/blob/master/linc/linc_timestamp_windows.cpp#L1)
- linc_stb / [h](https://github.com/snowkit/linc_stb/blob/master/linc/linc_stb_image.h#L3) / [cpp](https://github.com/snowkit/linc_stb/blob/master/linc/linc_stb_image.cpp#L1)
- linc_ogg / [h](https://github.com/snowkit/linc_ogg/blob/master/linc/linc_ogg.h#L3) / [cpp](https://github.com/snowkit/linc_ogg/blob/master/linc/linc_ogg.cpp#L1)
- linc_sdl / [h](https://github.com/snowkit/linc_sdl/blob/master/linc/linc_sdl.h#L3) / [cpp](https://github.com/snowkit/linc_sdl/blob/master/linc/linc_sdl.cpp#L1)
- linc_opengl / [h](https://github.com/snowkit/linc_opengl/blob/master/linc/linc_opengl.h#L3) / [cpp](https://github.com/snowkit/linc_opengl/blob/master/linc/linc_opengl.cpp#L1)

There are 2 or 3 headers that don't include hxcpp at all, I assume they don't need to? But all the code in the externs has hxcpp first. I'd be happy to get rid of this error that has not left us alone since whenever hxcpp introduced that, so if you have more suggestions @hughsando I'm happy to look more.

**Comment by hughsando** [comment]
You could start by removing hxcpp from the .h files.  This would then show errors where the cpp has not included  hxcpp.h first.
Or, you could try:
```cpp
#ifndef HXCPP_H
#include <hxcpp.h>
#endif
```
In the header file.

Also, you could try adding to the cl.exe flags in  msvc-toolchain.h:
```xml
 <flag value="-showIncludes" />
```
to show exactly what is including what.

**Comment by kamranrad1993** [comment]
thanks guys 
but what ca i do to fix this problem?

**Comment by kamranrad1993** [comment]
it`s work
thank

**Comment by underscorediscovery** [comment]
@kamranrad1993 you could: 

- delete `bin/` folder
- run `flow build --log 3` in terminal
- paste the whole log with all lines, somewhere like http://gist.github.com or http://pastebin.com

I don't have this error reproducing right now, so having the log with verbose detail will help.

**Comment by underscorediscovery** [comment]
ah, what changed to make it work?

**Comment by kamranrad1993** [comment]
add 
`#ifndef HXCPP_H
#include <hxcpp.h>
#endif`

instead of 
`#include <hxcpp.h>`

in every file that gives me this error
but now gives this error:

Link: luxe_empty
/usr/bin/ld: cannot find -lopenal
collect2: error: ld returned 1 exit status
flow / 
 build - stopping because of errors in hxcpp compile, while building arch 64

**Comment by underscorediscovery** [comment]
Ah ok, I see.

For the rest, please see the [setup guide](https://luxeengine.com/alpha/get/) for the instructions on setting up per platform.

**Comment by kamranrad1993** [comment]
i install libopneal-dev package and its work
thanks so much ;)

**Comment by underscorediscovery** [comment]
ok, glad it's working. 
I also pushed changes to all linc libs to shield guard the hxcpp include just in case that helps others too.
