### ISSUE TITLE
docs; update docs on website

### ISSUE THREAD

**Issue by anissen** [underscorediscovery/luxe#420]
The [docs for setting up luxe on the website](https://luxeengine.com/get/) is outdated compared to [the docs in the `docs-src` branch](https://github.com/underscorediscovery/luxe/blob/docs-src/luxe/md/setup.md).

**Comment by underscorediscovery** [comment]
Can you elaborate on what part specifically? I updated the website so the site is current, the docs-src is old.

**Comment by anissen** [comment]
Oh yeah, I thought it was the other way around!

However, the website docs are still outdated -- I was referring specifically to the guide saying `haxelib install hxcpp 3.2.205` rather than the most recent one. There's also other clearly outdated instructions such as
```
Install the latest stable Haxe release, 3.2.1
luxe requires Haxe 3.2.0+. 
Haxe 3.3.x and 3.4.x are not stable releases yet.
```

**Comment by underscorediscovery** [comment]
Right yea, this was an intentional concession while I/we test 3.4. 

While it works great so far there for a majority, there are still several pain points with hxcpp on Windows, Linux, and Android right out of the box being a dead end. I would prefer that new users aren't thrown directly into a mess until those things are made clearer, so I haven't updated this just yet.

I will soon though.

**Comment by anissen** [comment]
Roger that!
